# Generated by Django 4.2.4 on 2023-08-21 14:01

from django.db import migrations, models
import formapp.models
import formapp.snowflakes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('permissions', models.IntegerField(default=1)),
                ('creation_timestamp', models.FloatField()),
            ],
        ),
    ]
