# Generated by Django 4.2.4 on 2023-08-21 14:31

from django.db import migrations, models
import formapp.models
import formapp.snowflakes


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
