# Generated by Django 4.2.4 on 2023-08-21 14:58

from django.db import migrations, models
import formapp.models
import formapp.snowflakes


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_alter_user_id_alter_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False)),
                ('title', models.CharField(default='Untitled Form', max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('creation_timestamp', models.FloatField()),
                ('last_edit_timestamp', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
