# Generated by Django 4.2.4 on 2023-08-21 19:13

from django.db import migrations, models
import formapp.models
import formapp.snowflakes


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_form_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('form_id', formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False)),
                ('index', models.IntegerField()),
                ('question_type', models.IntegerField()),
                ('question', models.TextField(max_length=1000)),
                ('string_answer', models.TextField(blank=True, max_length=5000, null=True)),
                ('integer_answer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='user_id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
