# Generated by Django 4.2.4 on 2023-08-22 08:32

from django.db import migrations
import formapp.models
import formapp.snowflakes


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_question_form_question_count_alter_form_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='user_id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='form_id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=formapp.models.SnowflakeIDField(default=formapp.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
