# Generated by Django 4.2.4 on 2023-08-22 15:22

from django.db import migrations, models
import surway.models
import surway.snowflakes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False)),
                ('title', models.CharField(default='Untitled Form', max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('question_count', models.IntegerField(default=0)),
                ('require_login', models.BooleanField(default=False)),
                ('require_email', models.BooleanField(default=False)),
                ('creation_timestamp', models.FloatField()),
                ('last_edit_timestamp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('form_id', surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False)),
                ('user_id', surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False)),
                ('index', models.IntegerField()),
                ('question_type', models.IntegerField()),
                ('question', models.TextField(max_length=1000)),
                ('string_answer', models.TextField(blank=True, max_length=5000, null=True)),
                ('integer_answer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email_address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('permissions', models.IntegerField(default=1)),
                ('creation_timestamp', models.FloatField()),
            ],
        ),
    ]
