# Generated by Django 4.2.4 on 2023-08-22 18:45

from django.db import migrations
import surway.models
import surway.snowflakes


class Migration(migrations.Migration):

    dependencies = [
        ('surway', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='require_email',
            new_name='require_account',
        ),
        migrations.RemoveField(
            model_name='form',
            name='require_login',
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='user_id',
            field=surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='form_id',
            field=surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_id',
            field=surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=surway.models.SnowflakeIDField(default=surway.snowflakes.SnowflakeGenerator.generate_id, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
